language: node_js
node_js:
  - "node"
  - "9"

env:
  - SH=bash
  - PATH=${PATH//:\.\/node_modules\/\.bin/}

addons:
  apt:
    packages:
      - xvfb

install:
  - npm install -g yarn xvfb-maybe

before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start