language: node_js
node_js:
  - "node"
  - "9"

env:
  - SH=bash
  - PATH=${PATH//:\.\/node_modules\/\.bin/}

addons:
  apt:
    packages:
      - xvfb

install:
  - npm install -g yarn xvfb-maybe
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &